services:
  postgres:
    image: postgres:16-alpine
    container_name: car-rental-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car_rental_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - car-rental-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d car_rental_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  car-rental-network:
    driver: bridge
